version: '3.7'
services:
  db1:
    image: mysql:8.0.23
    platform: linux/x86_64 # to run in mac os m3
    restart: "no"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB1_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB1_USERNAME_NONROOT}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB1_PASSWORD_NONROOT}
      # Password for root access empty
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      # <Port exposed on host machine> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql58voldata01:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  db2:
    image: mysql:8.0.23
    platform: linux/x86_64 # to run in mac os m3
    restart: "no"
    env_file:
      - .env
    environment:
      MYSQL_DATABASE: ${DB2_NAME}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${DB2_USERNAME_NONROOT}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${DB2_PASSWORD_NONROOT}
      # Password for root access empty
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      # <Port exposed on host machine> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql58voldata02:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
# Names our volume
volumes:
  mysql58voldata01:
  mysql58voldata02:
